export const FETCH_CURRENT_DIALOG_REQUEST = 'FETCH_CURRENT_DIALOG_REQUEST'
export const FETCH_CURRENT_DIALOG_SUCCESS = 'FETCH_CURRENT_DIALOG_SUCCESS'
export const FETCH_CURRENT_DIALOG_FAILURE = 'FETCH_CURRENT_DIALOG_FAILURE'
