export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE'

export const RESET_AUTH_ERRORS = 'RESET_AUTH_ERRORS'

export const LOG_OUT = 'LOG_OUT'

export const SM_AUTH_REQUEST = 'SM_AUTH_REQUEST'
export const SM_AUTH_SUCCESS = 'SM_AUTH_SUCCESS'
export const SM_AUTH_FAILURE = 'SM_AUTH_FAILURE'
