export const SEND_RESET_EMAIL_REQUEST = "SEND_RESET_EMAIL_REQUEST"
export const SEND_RESET_EMAIL_SUCCESS = "SEND_RESET_EMAIL_SUCCESS"
export const SEND_RESET_EMAIL_FAILURE = "SEND_RESET_EMAIL_FAILURE"
