export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const AUTH_ON_PROGRESS = "AUTH_ON_PROGRESS";
export const AUTH_COMPLETE = "AUTH_COMPLETE";
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';